module.exports = str => require('./_brmap')(str, {
  'DOLPH MALL': 'Dolphin Mall',
  'KEND.VIA': 'Kendall via',
  'MDC KEND.': 'Miami Dade College (Kendall)',
  'MDC KENDALL': 'Miami Dade College (Kendall)',
  'MDC HOMESTEAD': 'Miami Dade College (Homestead)',
  'MDC NORTH': 'Miami Dade College (North)',
  'BISC BLVD': 'Biscayne Blvd',
  'BISC.BLVD.': 'Biscayne Blvd',
  'BISC. BLVD': 'Biscayne Blvd',
  'FT LAUD': 'Fort Lauderdale',
  ' KAT': ' West Kendall Transit Terminal',
  '163 ST MALL': '163rd Street Mall',
  'COCO GROVE': 'Coconut Grove',
  'MIA STATION': 'Airport Station',
  'CHILDREN HOSP': 'Nicklaus Children’s Hospital',
  'HIALEAH GRDNS': 'Hialeah Gardens',
  'DGLS RD': 'Douglas Road',
  'DOUGLAS RD STA': 'Douglas Road Station',
  'MIAMI BCH': 'Miami Beach',
  'HIA GRDNS': 'Hialeah Gardens',
  'DOUGLAS RD': 'Douglas Road',
  'FIU BISC BAY': 'FIU (Biscayne Bay)',
  'WSTCHSTR': 'Westchester',
  'OPALOCKA': 'Opa-Locka',
  'SO.MIAMI HTS': 'South Miami Heights',
  'DADELAND NO.': 'Dadeland North',
  'S.DADE': 'South Dade',
  'GVT CTR': 'Government Center',
  'DADELAND SOUTH': 'Dadeland South',
  'DADELAND SO': 'Dadeland South',
  'SO.MIAMI': 'South Miami',
  'MIA.SPGS': 'Miami Springs',
  'MIAMI GRDNS': 'Miami Gardens',
  'MERCY HOSP.': 'Mercy Hospital',
  'MIA BCH': 'Miami Beach',
  'LINC RD': 'Lincoln Road',
  'MIA STAT': 'Airport Station',
  'GOLDEN GLDS.': 'Golden Glades',
  'MDC-': 'Miami Dade College-',
  'MT SINAI HOSP': 'Mount Sinai Hospital',
  'HIA.TRI-RAIL STA': 'Hialeah Tri-Rail Station',
  'FLA.CITY': 'Flagler City',
  'FLA CITY': 'Flagler City',
  'MIAMI BEACH': 'Miami Beach',
  ' BEACH': ' Miami Beach',
  '.VIA': ' via',
  ' TO ': ' to ',
  ' VIA ': ' via ',
  '-VIA': ' via',
  'VIA ': ' via '
})
